google_maps_apis_project/google_maps_apis_project/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('main.urls', namespace="main")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

google_maps_apis_project/main/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns = [
    path('', views.HomeView.as_view(), name="home"),
    path('route', views.route, name="route"),
    path('map', views.map, name="map"),
]

google_maps_apis_project/main/models.py
from django.db import models

# Create your models here.

google_maps_apis_project/main/views.py
from django.shortcuts import render, redirect, reverse
from django.conf import settings
from django.views.generic.base import TemplateView


from google_maps_apis_project.mixins import Directions

class HomeView(TemplateView):
	'''
	Generic FormView with our mixin to display user home page
	'''
	template_name = "main/home.html"

def route(request):
	'''
	Basic view for routing
	'''
	context = {
	"google_api_key": settings.GOOGLE_API_KEY,
	"base_country": settings.BASE_COUNTRY}
	return render(request, 'main/route.html', context)

def map(request):
	'''
	Basic view for displaying a map
	'''
	lat_a = request.GET.get("lat_a", None)
	long_a = request.GET.get("long_a", None)
	lat_b = request.GET.get("lat_b", None)
	long_b = request.GET.get("long_b", None)
	address_a = request.GET.get("address_a", None)
	address_b = request.GET.get("address_b", None)

	# pass all variables to API call
	if lat_a and lat_b and long_a and long_b and address_a and address_b:
		directions = Directions(
			lat_a= lat_a,
			long_a=long_a,
			lat_b = lat_b,
			long_b=long_b,
			address_a=address_a,
			address_b=address_b,
			)
	else:
		return redirect(reverse('main:route'))

	context = {
	"google_api_key": settings.GOOGLE_API_KEY,
	"base_country": settings.BASE_COUNTRY,
	"lat_a": lat_a,
	"long_a": long_a,
	"lat_b": lat_b,
	"long_b": long_b,
	"origin": f'{lat_a}, {long_a}',
	"destination": f'{lat_b}, {long_b}',
	"directions": directions,

	}
	return render(request, 'main/map.html', context)

google_maps_apis_project/templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- visit https://fonts.google.com/specimen/Courier+Prime?preview.text_type=custom to get script-->
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Courier+Prime&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'main.css' %}"></link>

  <!-- https://cdnjs.com/libraries/toastr.js/latest -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.css" integrity="sha512-3pIirOrwegjM6erE5gPSwkUzO+3cTjpnV9lexlNZqvupR64iZBnOOTiiLPb9M36zpMScbmUNIcHUqKD47M719g==" crossorigin="anonymous" referrerpolicy="no-referrer" />


  <!-- This allows us to extend the head scripts in HTML docs that have special requirements-->


  {% block extend_head %}

  {% endblock %}

</head>
<body>

  <!-- This allows us to extend the nav bar in HTML docs that have special requirements-->
  {% include 'partials/nav.html' %}

  <div class="div-container">


    {% block content %}

    {% endblock %}

  </div>

  <!--visit https://code.jquery.com/ for jquery script-->
  <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>

  <!-- https://cdnjs.com/libraries/toastr.js/latest -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js" integrity="sha512-VEd+nq25CkR676O+pLBnDW09R7VQX9Mdiij052gVCp5yVH3jGtH70Ho/UUv4mJDsEdTvqRCFZg0NKGiojGnUCw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

  <!-- This allows us to extend the foot scripts in HTML docs that have special requirements-->
  {% block extend_footer %}

  {% endblock %}

  <script src="{% static 'main.js' %}"></script>


</body>
</html>

google_maps_apis_project/templates/main/home.html
{% extends 'base.html' %}
{% load static %}


{% block extend_head %}

{% endblock %}


{% block content %}

<h3>Channel Factory - Google Maps APIs Project</h3>

{% endblock %}


{% block extend_footer %}

{% endblock %}

google_maps_apis_project/templates/main/map.html
{% extends 'base.html' %}
{% load static %}


{% block extend_head %}


{% endblock %}


{% block content %}

<h3 id="map">A Google Maps APIs Project - Map</h3>

<div class="container">

  <table>
    <thead>
      <tr>
        <th>Field</th>
        <th>Value</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>Start Address</td>
        <td>{{directions.origin_address}}</td>
      </tr>
      <tr>
        <td>Start Latitude,Longitude</td>
        <td>{{directions.origin}}</td>      
      </tr>
      <tr>
        <td>Destination Address</td>
        <td>{{directions.destination_address}}</td>
      </tr>
      <tr>
        <td>Destination Latitude,Longitude</td>
        <td>{{directions.destination}}</td>      
      </tr>
      <tr>
        <td>Duration</td>
        <td>{{directions.duration}}</td>      
      </tr>
      <tr>
        <td>Distance using API</td>
        <td>{{directions.distance}}</td>      
      </tr>
      <tr>
        <td>Distance using Haversine Formula</td>
        <td>{{directions.distance_formula}}</td>
      </tr>

    </tbody>
  </table>
<br/><br/>
<h3>Bonus</h3>
  <table id="dir-table">
    <thead>
      <tr>
        <th>Directions</th>
        <th>Distance</th>
        <th>Duration</th>
      </tr>
    </thead>
    <tbody>
      {% for leg in directions.route %}
          <tr>
          <td>Leg {{ forloop.counter }}</td>
          <td></td>
          <td></td>  
        </tr>
        {% for dist, dur, text in leg.steps %}
        <tr>
          <td>{{text|safe}}</td>
          <td>{{dist}}</td>
          <td>{{dur}}</td>   
        </tr>
        {% endfor %}
      {% endfor %}
    </tbody>
  </table>

</div>

<div class="map-container">

   <div id="map-route"></div>


</div>

{% endblock %}

{% block extend_footer %}


<script type="text/javascript">

    var google_api_key = "{{google_api_key|safe}}";
    var lat_a = {{lat_a|safe}};
    var long_a = {{long_a|safe}};
    var lat_b = {{lat_b|safe}};
    var long_b = {{long_b|safe}};
    var origin = "{{origin|safe}}";
    var destination = "{{destination|safe}}";
    var directions = {{directions|safe}}

  </script>

  <script src="{% static 'google_maps.js' %}"></script>


{% endblock %}

google_maps_apis_project/templates/main/route.html
{% extends 'base.html' %}
{% load static %}


{% block extend_head %}


{% endblock %}


{% block content %}

<h3>A Google Maps APIs Project - Route</h3>

<div id="wrapper" class="container">

   <label for="id-google-address-a">Start Address</label>
   <input type="text" placeholder="Enter address" id="id-google-address-a" name="google_address_a">

   <label for="id-google-address-b">Destination Address</label>
   <input type="text" placeholder="Enter address" id="id-google-address-b" name="google_address_b">

   <input type="hidden" class="geo" id="id-lat-a" value="">
   <input type="hidden" class="geo" id="id-long-a" value="">
   <input type="hidden" class="geo" id="id-lat-b" value="">
   <input type="hidden" class="geo" id="id-long-b" value="">
   <input type="hidden" class="geo" id="id-address-a" value="">
   <input type="hidden" class="geo" id="id-address-b" value="">

</div>

{% endblock %}

{% block extend_footer %}


    <script type="text/javascript">

      var google_api_key = "{{google_api_key|safe}}";
      var base_country = "{{base_country|safe}}";

    </script>

  <script src="{% static 'google_places.js' %}"></script>


{% endblock %}

google_maps_apis_project/templates/partials/nav.html
<ul class="navbar">
  {% if "route" in request.path %}
  <a class="active" href="{% url 'main:route' %}">Route</a>
  {% else %}
  <a href="{% url 'main:route' %}">Route</a>
  {% endif %}

  {% if "map" in request.path %}
  <a class="active" href="{% url 'main:map' %}">Map</a>
  {% else %}
  <a href="{% url 'main:map' %}">Map</a>
  {% endif %}
</ul>